### ISSUE TITLE
Link change logout

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-cms#213]
1. select an external link (vimeo.com)
2. change from external link to internal page.
3. save
4. the user is logged out

because file-info id is looking for a wrong url:

file-info?id=vimeo.com which throws a 403 and forces a logout

**Comment by nadar** [comment]
An Error occurred while handling another error:
yii\web\NotFoundHttpException: The requested language 'de' does not exist in language table in /app/vendor/luyadev/luya-module-cms/src/Menu.php:709
Stack trace:
#0 /app/vendor/luyadev/luya-module-cms/src/Menu.php(322): luya\cms\Menu->loadLanguageContainer('de')
#1 /app/vendor/luyadev/luya-module-cms/src/Menu.php(213): luya\cms\Menu->getLanguageContainer('de')
#2 /app/vendor/luyadev/luya-module-cms/src/menu/Query.php(341): luya\cms\Menu->offsetGet('de')
#3 /app/vendor/luyadev/luya-module-cms/src/frontend/Bootstrap.php(51): luya\cms\menu\Query->one()
#4 [internal function]: luya\cms\frontend\Bootstrap->luya\cms\frontend\{closure}(Object(luya\web\ErrorHandlerExceptionRenderEvent))
#5 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(luya\web\ErrorHandlerExceptionRenderEvent))
#6 /app/vendor/luyadev/luya-core/web/ErrorHandler.php(31): yii\base\Component->trigger('onBeforeExcepti...', Object(luya\web\ErrorHandlerExceptionRenderEvent))
#7 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): luya\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#8 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#9 {main}
Previous exception:
yii\web\NotFoundHttpException: Unable to find the given storage file. in /app/vendor/luyadev/luya-module-admin/src/apis/StorageController.php:154
Stack trace:
#0 [internal function]: luya\admin\apis\StorageController->actionFileInfo('https://youtube...')
#1 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('file-info', Array)
#4 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/api-admin...', Array)
#5 /app/vendor/luyadev/luya-core/web/Application.php(46): yii\web\Application->handleRequest(Object(luya\web\Request))
#6 /app/vendor/yiisoft/yii2/base/Application.php(386): luya\web\Application->handleRequest(Object(luya\web\Request))
#7 /app/vendor/luyadev/luya-core/base/Boot.php(266): yii\base\Application->run()
#8 /app/vendor/luyadev/luya-core/base/Boot.php(208): luya\base\Boot->applicationWeb()
#9 /app/public_html/index.php(8): luya\base\Boot->run()
#10 {main}

**Comment by nadar** [comment]
http not found cms page parser shoud only be available for frontend not admin requests.
