### ISSUE TITLE
Unable to create a forwarding link

### ISSUE THREAD

**Issue by neoacevedo** [luyadev/luya-module-cms#419]
### What steps will reproduce the problem?

Create a new page. Select Forwarding tab. Fill the form to create a forwarding page.

### What is the expected result?

A new item for the top menu with a link to a directory or to an external URL link.

### What do you get instead? (A Screenshot can help us a lot!)

![imagen](https://github.com/luyadev/luya-module-cms/assets/438372/7844fd6e-cd10-47e3-ae40-c0de3b7e2d46)

```
yii\base\UnknownPropertyException: Setting unknown property: luya\cms\models\NavItemRedirect::anchor in /app/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\base\Component->__set('anchor', NULL)
#1 /app/vendor/yiisoft/yii2/base/Model.php(742): yii\db\BaseActiveRecord->__set('anchor', NULL)
#2 /app/vendor/yiisoft/yii2/base/Component.php(180): yii\base\Model->setAttributes(Array)
#3 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\base\Component->__set('attributes', Array)
#4 /app/vendor/luyadev/luya-module-cms/src/models/Nav.php(924): yii\db\BaseActiveRecord->__set('attributes', Array)
#5 /app/vendor/luyadev/luya-module-cms/src/admin/apis/NavController.php(482): luya\cms\models\Nav->createRedirect('0', '1', '2', 'Login', 'login', '2', 'http://localhos...', NULL, NULL, NULL)
#6 [internal function]: luya\cms\admin\apis\NavController->actionCreateRedirect()
#7 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('create-redirect', Array)
#10 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/api-cms-n...', Array)
#11 /app/vendor/luyadev/luya-core/web/Application.php(52): yii\web\Application->handleRequest(Object(luya\web\Request))
#12 /app/vendor/yiisoft/yii2/base/Application.php(384): luya\web\Application->handleRequest(Object(luya\web\Request))
#13 /app/vendor/luyadev/luya-core/base/Boot.php(251): yii\base\Application->run()
#14 /app/vendor/luyadev/luya-core/base/Boot.php(195): luya\base\Boot->applicationWeb()
#15 /app/public_html/index.php(8): luya\base\Boot->run()
#16 {main}
```

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

It can't be executed.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 2.3.1
| PHP Version      | 8.2 
| Platform         | nginx+php-fpm
| Operating system | Linux (docker).

**Comment by nadar** [comment]
run the migrations, seem you did a major update

**Comment by neoacevedo** [comment]
That's right. I didn't figured it.
